### PR TITLE
Direct Message

### PR DESCRIPTION
**Pull request by rhyolight**
Hi breznak. This pull-request is just a way for me to get ahold of you. I'd like to get your contact info so we can chat about Numenta. We're holding a hackathon soon around our open source offering (coming soon). If you are interested, please email me at matt@numenta.org.

### CODE REVIEW

**Comment by rhyolight** [comment]
Is it creepy that I'm still trying to contact you? Seriously. :) http://numenta.org We'd love you to participate. I'm not a recruiter, if that's what you're thinking.

**Comment by linkerlin** [comment]
Hi,breznak!
    I cannot build the current version of code. Could you make it build-able? Thanks!

**Comment by breznak** [comment]
Hi @linkerlin !

I'm pleased with your interest in the java CLA version. Quite long ago I've moved to the unified development at https://github.com/numenta/nupic where lot of improvements happened. I'd suggest you join us there! :smile: 

If you however need to use my java version, I will try to see I what state I left it off during the weekend. 

Best regards, breznak

**Comment by breznak** [comment]
Those were the times :wink:

**Pull request closed without merging**
